/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
      xyz:[
         {
           id:"intro",
           type:"doc",
         },
        {
          type:"category",
          label:"tutorial-basics",
          items:[
            "tutorial-basics/create-a-blog-post",
            "tutorial-basics/create-a-page",
          {
            type:"category",
            label:"subcategory",
            items:[
              "tutorial-extras/translate-your-site",
              {
                  type:"category",
                  label:"sub-sub category",
                  items:[
                    "tutorial-extras/manage-docs-versions"
                  ],
              }    
          ],
          },
        ],
        }
      ],


      docs:[
         {
          id:"menu1/welcome",
          type: "doc",
         },
        {
          type:"category",
          label:"folder_1",
          items:["menu1/folder_1/sql file"],
        },
        {
         type:"category",
         label:"folder_2",
         items:["menu1/folder_2/Trilogix overview"],
       },],

     sidebar1:[
       {
         id:"menu2/welcome",
         type: "doc",
      },
      
       {
         type:"category",
         label:"folder_1",
         items:["menu2/folder_1/image file"],
       },
      {
        type:"category",
        label:"folder_2",
        items:["menu2/folder_2/file4"],
      }
        ]
 };

module.exports = sidebars;
